# image: rnsloan/wasm-pack:1.0.0
image: registry.gitlab.com/ogadaki/docker/wasm-pack:1.0

pages:
  cache:
    paths:
      - node_modules/

  script:
    - yarn install
    - yarn run build
    - mv dist public

  artifacts:
    paths:
    - public
  only:
  - master
